name: Run tests
on: [push]
jobs:
  testDebugUnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
      - run: ./gradlew testDebugUnitTest --stacktrace
  connectedDebugAndroidTest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          script: ./gradlew connectedDebugAndroidTest --stacktrace
